# Generated by Django 4.2.11 on 2024-06-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, verbose_name='Nazwa produktu')),
            ],
            options={
                'verbose_name_plural': 'Produkty',
            },
        ),
        migrations.CreateModel(
            name='ShoppingLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lists_name', models.CharField(error_messages={'unique': 'Lista o takiej nazwie już istnieje!'}, max_length=30, unique=True, verbose_name='Nazwa listy')),
                ('products', models.ManyToManyField(to='products.products', verbose_name='Produkty')),
            ],
            options={
                'verbose_name_plural': 'Listy zakupów',
            },
        ),
    ]
