# Generated by Django 5.0.2 on 2024-03-03 15:55

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ShoppingLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lists_name', models.CharField(default=builtins.id, max_length=30)),
                ('products', models.ManyToManyField(to='products.products')),
            ],
        ),
    ]
