# Generated by Django 5.0.2 on 2024-03-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_quantity_shoppinglists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglists',
            options={'verbose_name_plural': 'Listy zakupów'},
        ),
        migrations.AlterField(
            model_name='shoppinglists',
            name='lists_name',
            field=models.CharField(max_length=30),
        ),
    ]
