# Generated by Django 4.2.11 on 2024-05-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_options_alter_shoppinglists_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(error_messages={'unique': 'Taki produkt już istnieje!'}, max_length=30, unique=True, verbose_name='Nazwa produktu'),
        ),
        migrations.AlterField(
            model_name='shoppinglists',
            name='lists_name',
            field=models.CharField(error_messages={'unique': 'Lista o takiej nazwie już istnieje!'}, max_length=30, unique=True, verbose_name='Nazwa listy'),
        ),
    ]
